POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "39-44-5323523"
}

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "12-43-234345"
}

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Poppendieck",
    "number": "39-23-6423122"
}

### Missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "246-813579"
}

### Missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Random person",
    "number": ""
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "rr",
    "number": "12345"
}
